(function() {var implementors = {};
implementors["range_set"] = [{text:"impl&lt;A&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"range_set/struct.RangeSet.html\" title=\"struct range_set::RangeSet\">RangeSet</a>&lt;A&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;&lt;A as Array&gt;::Item: <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a>,&nbsp;</span>",synthetic:true,types:["range_set::RangeSet"]},{text:"impl&lt;'a, A, T&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"range_set/struct.Iter.html\" title=\"struct range_set::Iter\">Iter</a>&lt;'a, A, T&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;A: <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a>,<br>&nbsp;&nbsp;&nbsp;&nbsp;T: <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a>,&nbsp;</span>",synthetic:true,types:["range_set::Iter"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"enum\" href=\"range_set/range_compare/enum.RangeCompare.html\" title=\"enum range_set::range_compare::RangeCompare\">RangeCompare</a>",synthetic:true,types:["range_set::range_compare::RangeCompare"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"enum\" href=\"range_set/range_compare/enum.RangeDisjoint.html\" title=\"enum range_set::range_compare::RangeDisjoint\">RangeDisjoint</a>",synthetic:true,types:["range_set::range_compare::RangeDisjoint"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"enum\" href=\"range_set/range_compare/enum.RangeIntersect.html\" title=\"enum range_set::range_compare::RangeIntersect\">RangeIntersect</a>",synthetic:true,types:["range_set::range_compare::RangeIntersect"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
